---
title: "Machine Learning with Caret"
author: "Jesse Cambon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../R") })
output:
  github_document:
    toc: true
    toc_depth: 2
---

Demonstrate a machine learning workflow with caret

## References
* https://topepo.github.io/caret/model-training-and-tuning.html
* https://cran.r-project.org/web/packages/caretEnsemble/vignettes/caretEnsemble-intro.html 

## Setup

```{r setup,warning=F,message=F}
library(mlbench) # machine learning reference datasets
library(tidyverse)
library(broom)
library(caret)
library(skimr)
library(knitr)
library(kableExtra)

data(BreastCancer) # load

# Set seed for reproducibility
set.seed(45)
```


## Build Model

```{r models,message=F,results=F,warning=F}
#skim(BreastCancer)

BC <- BreastCancer %>% as_tibble() %>%
  dplyr::select(-Id) %>%
  # should really use imputation but we'll just drop nas for now
  drop_na() 

# Use k-fold cross-validation
TC <- trainControl(method="cv", number=5)

# Train some models

# Neural Net
nnet <- train(Class ~ . , BC,method='nnet',trControl=TC,verbose=FALSE)

# Gradient Boosted Machine
gbm <- train(Class ~ . , BC,method='gbm',trControl=TC)

# Radial SVM
svmrad <- train(Class ~ . , BC,method='svmRadial',trControl=TC)

# Elastic-net
glmnet <- train(Class ~ . , BC,method='glmnet',trControl=TC,tuneLength=5)

# Logistic regression - did not converge
glm <- train(Class ~ . , BC,method='glm',trControl=TC)

```


```{r}

# Look at results of Glmnet model

# Extract coefficients from optimal model
glm_coeff <- coef(glmnet$finalModel,glmnet$finalModel$lambdaOpt) %>% 
  as.matrix() %>% as.data.frame() %>%
  rownames_to_column('Variable') %>%
  as_tibble() %>%
  rename(Coefficient=2) %>%
  arrange(desc(abs(Coefficient)))


# Combine variable importance data with coefficients
varImportance <- varImp(glmnet)$importance %>% 
  rownames_to_column('Variable') %>%
  rename(Importance=2) %>%
  arrange(desc(Importance)) %>%
  full_join(glm_coeff,by='Variable') %>%
  filter(Coefficient != 0) 
```




```{r results}
resamps <- resamples(list(nnet=nnet,
                          glmnet=glmnet,
                          svmrad=svmrad,
                          gbm=gbm,
                          glm=glm))

# Accuracy comparison
dotplot(resamps, metric = "Accuracy")

# Difference in accuracy
bwplot(diff(resamps))
```

## Glmnet (Elastic Net) Model

```{r,results='asis',warning=F,message=F}
kable(varImportance,format='markdown') %>%
  kable_styling(bootstrap_options = c("striped",'border'))
```
