---
title: "Geospatial Analysis"
author: "Jesse Cambon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
---


Note: Use devtools::install_github("hrbrmstr/albersusa") to install albersusa

https://github.com/bhaskarvk/colormap


c("B23025_005E", # labor force size
              'B01003_001E', # population
              'B25056_001E'), # rent

https://github.com/mtennekes/tmap/tree/master/demo/USChoropleth 

https://mran.revolutionanalytics.com/snapshot/2016-03-22/web/packages/tmap/vignettes/tmap-nutshell.html

```{r,warning=F,message=F}
library(tidyverse)
library(tidycensus) # census data
library(ggplot2)
library(sf)
library(tmap) # thematic mapping
library(viridis) # color scheme

options(tigris_use_cache = TRUE)

```


```{r locale}
# us_county_income <- get_acs(geography = "county", variables = "B19013_001", geometry = TRUE)
# 
# qtm(us_county_income, fill = "estimate")


# us <- get_acs(geography = "county", 
#               variables = 'B25064_001E', # median gross rent
#               geometry = TRUE) 
# 
# qtm(us, fill = "estimate")


# Rent in Seattle
sea <- get_acs(geography = "tract", 
              variables = "B25064_001E",  # median gross rent
              state = "WA", 
              county = "King", 
              geometry = TRUE)

qtm(sea, fill = "estimate")

#vars <- load_variables(2016,'acs1') # view census variables
```
    
http://www.robinlovelace.net/presentations/spatial-tidyverse.html#11
https://cran.r-project.org/web/packages/wbstats/vignettes/Using_the_wbstats_package.html


```{r}
#library(maptools)
#library(scales)
library(ggplot2)
library(albersusa) # US country map
library(ggthemes)
library(spData)
library(wbstats)
library(tmap)
library(maps)
library(wesanderson)

tm_shape(world, projection="wintri") +
        tm_polygons("lifeExp", title=c("Life expectancy"),
          style="pretty", palette='RdYlGn') +
        tm_style('grey') + tmap_mode("plot")

tm_shape(world, projection="wintri") +
        tm_polygons("gdpPercap", title=c("GDP Per Capita"),
          style="pretty", palette='RdYlGn') +
        tm_style('grey') + tmap_mode("plot")

map('county', 'virginia', fill = TRUE, col = wes_palette('Moonrise3'))



```


```{r,include=F,eval=F}


View(worldbank_df)

qtm(world)

Arrests <- USArrests %>% rownames_to_column('State') %>%
  as_tibble()
  
us <- usa_composite() %>% forti
%>% 
  left_join(Arrests,by=c('name'='State')) 

  left_join(U)



us_map <- fortify(usa_composite() , region="fips_state")
ggplot(us_map, aes(map_id=fips_state,fill=pop_2014)) +
  geom_map(map=us_map, color='#ffffff', size=0.1) + 
  expand_limits(x=us_map$long,y=us_map$lat) +
  theme_map() +  
  theme(legend.position="right") +
  coord_map("albers", lat0=30, lat1=40) +
   scale_fill_viridis(options='magma')
  # scale_fill_colormap("State Population\n(2014 Estimates)", labels=comma,
                      # colormap = colormaps$copper, reverse = T, discrete = F)
```



