---
title: "Time Series Modeling"
author: "Jesse Cambon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
---



## References
* https://feasts.tidyverts.org/
* https://github.com/tidyverts/tsibble
* http://pkg.robjhyndman.com/forecast/
* https://business-science.github.io/sweep/index.html
* https://cran.rstudio.com/web/packages/sweep/vignettes/SW01_Forecasting_Time_Series_Groups.html
* https://www.r-bloggers.com/climate-change-modeling-140-years-of-temperature-data-with-tsibble-and-fable/


## Setup

```{r setup}
library(nycflights13) 
library(tsibbledata)
library(wesanderson) # color palettes
library(tidyverse)
library(tsibble)
#library(skimr)
#library(feasts) # Removed for now since it breaks the forecast package
library(lubridate)
library(forecast)


# Set default ggplot theme
theme_set(theme_bw() +
  theme(legend.position = "top",
            plot.subtitle= element_text(face="bold",hjust=0.5),
            plot.title = element_text(lineheight=1, face="bold",hjust = 0.5)))

```

Import Data and Convert to Tsibble format

```{r}
weather <- nycflights13::weather %>% 
  select(origin, time_hour, temp, humid, precip)

weather_tsbl <- as_tsibble(weather, key = origin, index = time_hour)
```

Fill Missing Gaps


```{r}
nrow(ansett)

# Fill gaps and filter
ansett_fill <- ansett %>%
  filter(Airports == 'MEL-SYD') %>%
  fill_gaps(Passengers = 0)

nrow(ansett_fill)
```

```{r}
ggplot(ansett_fill,
          aes(x=Week,y=Passengers)) +
  geom_area(aes(fill = Class), alpha = 0.8) +
scale_fill_manual(values=wes_palette('Moonrise2')) +
scale_y_continuous(labels=scales::comma) +
labs(title='',
     caption='') +
theme(legend.title = element_blank(),
      legend.position='right') 
```

Test forecast package

```{r}

USAccDeaths %>% 
  stl(s.window='periodic') %>%
  forecast() %>%
  autoplot()


AirPassengers %>%
  stlf(lambda=0) %>%
  autoplot()
```

Test feasts package

Feasts package unfortunately breaks the forecast package

```{r}

# 
# aus_production %>% gg_subseries(Beer)+ theme(
#       legend.position='right') 
# 
# aus_production %>% STL(Beer ~ season(window = Inf)) %>% autoplot()
```

