---
title: "Bayesian Basics"
author: "Jesse Cambon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
---


```{r knit-settings, include=FALSE}
library(here)
source(here("rmd_config.R"))
```

* https://github.com/easystats/see/issues/48
* https://easystats.github.io/see/articles/bayestestR.html
* https://cran.r-project.org/web/packages/bayestestR/vignettes/bayes_factors.html

```{r}
library(rstanarm)
library(tidyverse)
library(bayestestR)
library(bayesplot)
library(wesanderson)
library(broom.mixed)

options(mc.cores = parallel::detectCores()) 

model <- stan_glmer(extra ~ group + (1 | ID), data = sleep,
                  prior = normal(0, 3, autoscale = FALSE))

summary(model)

tidy(model)
```

https://github.com/easystats/see/issues/48

```{r}
#My_first_BF <- bayesfactor_parameters(model, null = c(-1, 1))

density <- estimate_density(model)
sim_prior <- simulate_prior(model)
density_prior <- estimate_density(sim_prior)

# Combine density for prior and posterior distributions
post_prior <- density %>% mutate(type = 'posterior') %>%
  bind_rows(density_prior %>% mutate(type = 'prior'))

```

Plot the prior and posterior distributions for the fixed effects

```{r}
ggplot(data = post_prior, aes(x = x ,y = y, fill = type)) + 
  theme_bw() +
  facet_wrap(~Parameter, ncol = 1, scales='free') +
  geom_ribbon( mapping = aes(
    ymin = 0,
    ymax = y  ),
  alpha = .8) +   
  scale_fill_manual(values=c('steelblue', 'grey'))


#  scale_x_continuous(expand=expand_scale(mult = c(-.4, -.4)))
```

```{r}
mcmc_trace(model)
mcmc_areas(model)
```


https://easystats.github.io/see/articles/bayestestR.html

```{r}
plot(model)

p_direction(model)
```

```{r, fig.height = 10, fig.width = 8}
plot(p_direction(model, effects = "all", component = "all"))
```


Check posterior distribution

```{r}
pp_check(model)

pp_check(model, plotfun = "hist")

pp_check(model, plotfun = "intervals")
```


```{r}
ppc_intervals_grouped(
  y = sleep$extra,
  yrep = posterior_predict(model),
  x = as.numeric(sleep$group),
  prob = 0.5,
  group = sleep$ID
) 
```

