---
title: "Parsnip"
author: "Jesse Cambon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
---

Experiment with Bayesian modeling techniques on the titianic dataset.

```{r knit-settings, include=FALSE}
library(here)
source(here("rmd_config.R"))
```

* http://biostat.mc.vanderbilt.edu/wiki/pub/Main/StatisticalComputingSeries/bayes_reg_rstanarm.html

```{r}
# install.packages("rstanarm") # may take a while
library(rstan)
library(rstanarm)
library(ggplot2)
library(bayesplot)

# this option uses multiple cores if they're available
options(mc.cores = parallel::detectCores()) 
```
```{r}
glm_post1 <- stan_glm(dist~speed, data=cars, family=gaussian)
```
```{r}
summary(glm_post1)
```

```{r}
stan_hist(glm_post1, pars=c("speed"), bins=40)

```

```{r}
prior_summary(glm_post1)
```

```{r}
posterior_vs_prior(glm_post1, group_by_parameter = TRUE, pars=c("(Intercept)"))
posterior_vs_prior(glm_post1, group_by_parameter = TRUE, pars=c("speed","sigma"))
```


# Archive


References: 
* https://m-clark.github.io/workshops/bayesian/04_R.html
## Setup

```{r}
library(PASWR) #titanic3 dataset
library(tidyverse)
library(rstanarm)
options(mc.cores = parallel::detectCores()) # for using multiple cores
```

Data manipulation and imputation

```{r}
titanic <- titanic3 %>% as_tibble() %>%
  mutate(sex=str_to_title(sex))

library(mice)
titanic_imputed <- mice(titanic %>% select(sex,pclass,age), method = 'pmm', maxit=80,seed = 3530,printFlag=F)

# Add imputed Data
titanic_imp <- complete(titanic_imputed,5) %>%
  bind_cols(titanic %>% select(survived,age,fare) %>% rename(age_orig=age)) %>%
  mutate(imputed=case_when(is.na(age_orig) ~ 'Imputed', TRUE ~ 'Original')) %>%
  drop_na(fare) # drop one row where fare is NA
```

Fit models

https://m-clark.github.io/workshops/bayesian/04_R.html#rstanarm

```{r}

stan_fit <- stan_glm(survived ~ sex + pclass + age,data=titanic_imp,
  family=binomial(link="logit"),
  iter=2000, warmup=1000)

# Fit a logistic regression for comparison
log_fit <- glm(survived ~ sex + pclass + age ,family=binomial(link="logit"),data=titanic_imp)

```

## Insights



* https://easystats.github.io/see/articles/bayestestR.html
* https://easystats.github.io/see/ 

```{r}
library(bayestestR)
library(see)
library(insight)
library(rstanarm)
#theme_set(theme_modern())

model <- stan_glm(Sepal.Length ~ Petal.Width * Species, data = iris)

result <- estimate_density(model)

plot(result, stack=FALSE,priors = TRUE)
```





```{r}

prior_summary(stan_fit)

library(insight)
priors <- get_priors(stan_fit)

parameters <- get_parameters(stan_fit)
```





```{r}
summary(stan_fit,probs=c(.025, .975), digits=3)
summary(log_fit)
```

```{r}
pp_check(stan_fit)
```

