---
title: "Bayesian Modeling"
author: "Jesse Cambon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
---

```{r knit-settings, include=FALSE}
library(here)
source(here("rmd_config.R"))
```

References:
* http://appliedpredictivemodeling.com/data
* http://faculty.marshall.usc.edu/gareth-james/ISL/data.html

## Setup

```{r,message=F,warning=F}
#library(AppliedPredictiveModeling) # datasets
library(ISLR) # datasets
library(skimr)
library(tidyverse)
library(wesanderson)
library(rstanarm)
library(bayestestR)
library(insight)
library(bayesplot)
library(broom)
library(rsample)
library(knitr)
library(jcolors)
library(patchwork)

num_cores <-  parallel::detectCores()
options(mc.cores = num_cores)

set.seed(42) # for reproducibility

# C/V split
split <- initial_split(Carseats, prop = 1/2)
carseat_train <- training(split) %>% as_tibble()
carseat_test  <- testing(split) %>% as_tibble()
```

Fit models

```{r}
lm_model <- lm(Sales ~ Advertising + Price, data = carseat_train)
stan_model <- stan_glm(Sales ~ Advertising + Price, data = carseat_train)
```

```{r}
tidy(lm_model) %>% kable()
tidy(stan_model) %>% kable()
```

```{r}
prior_summary(stan_model)

pointest <- point_estimate(stan_model)
```


Make predictions using the posterior distribution

```{r}
post_pred <- posterior_predict(stan_model,new_data = carseat_test,draws = 1000) %>%
  as_tibble()

#post_pred_density <- estimate_density(post_pred)

```

Look at the posterior prediction distribution for a single observation

```{r}

row_num <- quo(`25`)
ggplot(aes(x=!!row_num),data=post_pred) + geom_density() + theme_minimal()

# Take a look at that same row number
print(carseat_test %>% select(Sales, Advertising, Price) %>% slice(as.numeric(as_label(row_num))))
```

Draw from the prior distribution

```{r}
# Simulate prior with bayestestR package
prior <- simulate_prior(stan_model) %>%
  pivot_longer(everything(),names_to='Parameter')

# Simulate Posterior with insight package
posterior <- get_parameters(stan_model,iterations=10000) %>% 
  pivot_longer(everything(),names_to='Parameter')

prior_posterior <- prior %>% mutate(Distribution='Prior') %>% 
  bind_rows(posterior %>% mutate(Distribution='Posterior'))

```

```{r}
ggplot(data=prior_posterior %>% filter(!str_detect(Parameter,'Intercept')),aes(x=value,color=Distribution)) + 
  facet_wrap(Parameter~Distribution,scales='free') +
  theme_minimal() +
  theme(legend.position='top',
        legend.title=element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  geom_density() + ggtitle('Prior vs Posterior Distributions') +
  xlab('') + ylab('') 
  
```



Plot priors
```{r}
ggplot(data=prior %>% filter(!str_detect(Parameter,'Intercept')),aes(x=value,color=Parameter)) + 
  facet_grid(~Parameter,scales='free_x') +
  theme_minimal() +
  theme(legend.position='top',
        plot.title = element_text(hjust = 0.5)) +
  geom_density() + ggtitle('Prior Distributions') +
ggplot(data=posterior %>% filter(!str_detect(Parameter,'Intercept')),aes(x=value,color=Parameter)) + 
  facet_grid(~Parameter,scales='free_x') +
  theme_minimal() +
  theme(legend.position='top',
        plot.title = element_text(hjust = 0.5)) +
  geom_density() + ggtitle('Posterior Distributions') 
```


```{r}
mcmc_areas(stan_model,pars=c('Advertising','Price')) + theme_bw()
mcmc_intervals(stan_model,pars=c('Advertising','Price')) + theme_bw()
posterior_vs_prior(stan_model)
```


Posterior Prediction Check

```{r}
pp_check(stan_model)
```


Manually plot the outcome distribution to compare to the posterior check plot above 

```{r}
ggplot(aes(x=Sales),data=carseat_train) + geom_density() + theme_minimal()
```



