---
title: "Distribution Sampling and Hypothesis Testing"
author: "Jesse Cambon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
---

```{r knit-settings, include=FALSE}
library(here)
source(here("rmd_config.R"))
```

References:
* http://appliedpredictivemodeling.com/data
* http://faculty.marshall.usc.edu/gareth-james/ISL/data.html

```{r,message=F,warning=F}
library(tidyverse)
library(bayestestR)
library(BayesFactor)
library(jcolors)
library(infer)
library(broom)
library(knitr)

set.seed(42) # for reproducibility
```

Perform sampling

```{r}
bernouli_sample <- rbernoulli(10,p=0.9) # T/F
uniform = runif(10,-4,4)

num_rows <- 1000

dist <- 
  tibble(
    cauchy=rcauchy(num_rows,0,0.5),
    norm_sample = rnorm(num_rows,0,0.5),
    beta_sample = rbeta(num_rows,0,1)
) %>%
  pivot_longer(everything(),values_to='value',names_to='distribution')


# Distributions used for count data
count_dist <- tibble(poisson= rpois(num_rows,2),
                      `negative binomial`=rnbinom(num_rows,1,mu=2),
                      binom_sample = rbinom(num_rows,9,.25),
                      weibull=rweibull(num_rows,1.4)
                      ) %>%
  pivot_longer(everything(),values_to='value',names_to='distribution')
```

Compare some distributions

```{r}
ggplot(data=dist,aes(x=value,color=distribution)) + 
#  facet_wrap(~distribution,ncol=1) +
  scale_x_continuous(limits =c(-3,3)) +
  theme_minimal() +
  theme(legend.position='top') +
  geom_density(alpha=0.8) +
  scale_color_jcolors('default') + 
  xlab('') + ylab('')
```

Poisson v Neg Binomial v Weibull

```{r}
ggplot(data=count_dist,aes(x=value,color=distribution)) + 
#  facet_wrap(~distribution,ncol=1) +
  scale_x_continuous(limits =c(0,8)) +
  theme_minimal() +
  theme(legend.position='top') +
  geom_density(alpha=0.8) +
  scale_color_jcolors('default') + 
  xlab('') + ylab('')
```


## Significance Testing

### T-test (Frequentist version)

```{r}
t.test(trees$Height)
```

Simulate some data and run more T-tests

```{r}
compare_norms <- rnorm(100,25,10) %>%
  as_tibble() %>% rename(sample1=value) %>%
  mutate(sample2 = rnorm(100,28,10))

results <- t.test(compare_norms$sample1,compare_norms$sample2)
results
```

Tidy T-test (infer package)

https://infer.netlify.app/

```{r}
compare_norms_long <- 
  compare_norms %>%
  pivot_longer(everything(),names_to='sample', values_to='value')

compare_norms_long %>%
  t_test(value ~ sample,order=c('sample1','sample2')) %>%
  kable()
```


### Bayesian T-test

https://easystats.github.io/bayestestR/articles/example2.html
```{r}
bayes_result <- BayesFactor::ttestBF(compare_norms$sample1,compare_norms$sample2)
bayes_result
```
```{r}
describe_posterior(bayes_result) %>% kable()
```

