---
title: "Multilevel Models"
author: "Jesse Cambon"
date: "`r format(Sys.time(), '%B, %Y')`"
output:
  github_document:
    toc: true
---

```{r knit-settings, include=FALSE}
library(here)
source(here("rmd_config.R"))
```

References:

- https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf
- https://www.rensvandeschoot.com/tutorials/lme4/


```{r setup, message = F, warning = F}
library(lme4)
library(broom.mixed)
library(rstanarm)
library(bayesplot)
library(tidyverse)
library(bayestestR)
```


```{r}
fm1 <- lmer(Reaction ~ Days + (1 + Days | Subject), data = sleepstudy)
```

```{r}
#sleepstudy
```
```{r}
# Overall Trend
sleepstudy %>%
  ggplot(aes(x = Days, y = Reaction)) +
  geom_point() + geom_smooth(method = 'lm')

#
sleepstudy %>%
  ggplot(aes(x = Days, y = Reaction)) +
  facet_wrap(~Subject) +
  geom_point() + geom_smooth(method = 'lm')
```



```{r}
tidy(fm1)
glance(fm1)
```

## Bayesian approach

https://mc-stan.org/users/documentation/case-studies/tutorial_rstanarm.html

```{r}
bm1 <- stan_lmer(Reaction ~ Days + (1 + Days | Subject), data = sleepstudy)
```

```{r}
pp_check(bm1)
```



```{r, fig.height = 8, fig.width = 5}
mcmc_areas(bm1)
```

Posterior predictive check

```{r}
ppc_ribbon_grouped(
  y = sleepstudy$Reaction,
  yrep = posterior_predict(bm1),
  x = sleepstudy$Days,
  prob = 0.5,
  group = sleepstudy$Subject
) 
```

```{r}
plot(p_direction(bm1, effects = "fixed", component = "all"))
plot(p_direction(bm1, effects = "random", component = "all"))

p_direction(bm1, effects = 'all')
```


```{r}
summary(bm1)
```

