---
title: "Power Analysis"
author: "Jesse Cambon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
---

```{r knit-settings, include=FALSE}
library(knitr)
library(stringr)
library(here)
# get name of file during knitting and strip file extension
rmd_filename <- str_remove(knitr::current_input(),"\\.Rmd")
print(rmd_filename)
knitr::opts_chunk$set(fig.path = str_c(here::here("rmd_images",rmd_filename),'/'),echo=TRUE) # image path
```



```{r}
library(pwr)
pwr.2p.test(
       h=ES.h(0.6,0.8),
       n=NULL,
       sig.level=0.05,
       power=0.80,
       alternative="two.sided")

```


```{r}
library(pwr)
power.prop.test(n = NULL, 
                p1 = .6, 
                p2 = .8,
                power=0.8,
                sig.level=0.05,
                alternative="two.sided"
                ) 
```


### Additional References 

* [Biostat Handbook – Power Analysis](http://www.biostathandbook.com/power.html)
* [Biostat Handbook - Hypothesis Testing](http://www.biostathandbook.com/hypothesistesting.html)
* [UCLA Intro to Power Analysis](https://stats.idre.ucla.edu/other/mult-pkg/seminars/intro-power/)
* [An online power calculator for proportions](https://www.stat.ubc.ca/~rollin/stats/ssize/b2.html)
* [The pwr R package](https://cran.r-project.org/web/packages/pwr/vignettes/pwr-vignette.html) – a popular R package used for power analysis

