---
title: "Machine Learning on the Vehicles Dataset"
author: "Jesse Cambon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
---

Predict vehicle fuel economy.


## Setup

```{r setup,warning=F,message=F}
library(fueleconomy)
library(tidyverse)
library(broom)
library(caret)
library(skimr)
library(knitr)
library(kableExtra)

# Set seed for reproducibility
set.seed(45)
```



## Build Model

```{r models,message=F,results=F,warning=F}

vehicles_clean <- vehicles %>%
  filter(displ !=0 & !is.na(cyl))

skim(vehicles_clean)

lm_fit <- lm(log(cty) ~ drive + year + log(cyl) + log(displ),
             data=vehicles_clean)

lm_stats <- glance(lm_fit)
lm_terms <- tidy(lm_fit,conf.int=T)


```

```{r}

```




# Train Models With Caret

```{r caret}
# Regression formula with no variable transformations
alpha_formula <- cty ~ year + fuel +
               cyl + displ

# Regression formula with transformed variables
log_formula <- log(cty) ~ drive + year + fuel +
               log(cyl) + log(displ)



# Use k-fold cross-validation
TC <- trainControl(method="cv", number=5)

caret_lm <- train(alpha_formula , vehicles_clean,method='lm',trControl=TC)
caret_gamSplines <- train(alpha_formula,vehicles_clean,method='gamSpline',trainControl=TC)


caret_glm <- train(log_formula , vehicles_clean,method='glm',trControl=TC)
#caret_nb <- train(alpha_formula,vehicles_clean,method='glm.nb',trainControl=TC)
# gam with loess and splines from gam package
#caret_gamLoess <- train(alpha_formula,vehicles_clean,method='gamLoess',trainControl=TC)

caret_glmnet <- train(log_formula , vehicles_clean,method='glmnet',trControl=TC,tuneLength=5)
caret_knn <- train(log_formula , vehicles_clean,method='knn',trControl=TC)

```

## Compare LM to GAM

```{r results}
resamps <- resamples(list(lm=caret_lm,
                          gamSplines=caret_gamSplines))

# Accuracy comparison
dotplot(resamps,metric='Rsquared')

# Difference in accuracy
bwplot(diff(resamps,metric='Rsquared'))
```

## Compare Models

```{r results}
resamps <- resamples(list(lm=caret_lm,
                          glm=caret_glm,
                          glmnet=caret_glmnet,
                          knn=caret_knn))

# Accuracy comparison
dotplot(resamps,metric='Rsquared')

# Difference in accuracy
bwplot(diff(resamps,metric='Rsquared'))
```
